// STEP 2: Action types
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const SET_USERPROFILE = "SET_USERPROFILE";

export const CREATE_EXPERIENCE = "CREATE_EXPERIENCE";
export const READ_EXPERIENCE = "READ_EXPERIENCE";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const FILTER_EXPERIENCES = "FILTER_EXPERIENCES";
export const CLEAR_FORM = "CLEAR_FORM";

export const GET_EXPERIENCES = "GET_EXPERIENCES";

export const UPDATE_FORM = "UPDATE_FORM";
export const EDIT = "EDIT";
